### ISSUE TITLE
How to use this page

### ISSUE THREAD

**Issue by tpridge** [Bonitasoft-Community/page_awacs#1]
Hi,

I tried to import this page into Bonita CE v.7.1.5.  It gave me compilation errors and also gave me errors when I tried access it from an application.  Could instructions on how to use this page be included ?

Brad P.

**Comment by pierre-yves-monnet** [comment]
Hello,
I found some Subscription reference in the import, which are not needed. 
I produce a new release, could you check it please ? Not easy for me : I have a Subscription licence...

**Comment by tpridge** [comment]
Hi,

I tried the new release on 7.1.5 CE & 7.2.2 CE, and it worked great.  It is a cool looking page.

Thanks.
